### ISSUE TITLE
Week 21: Refining algorithm.

### ISSUE THREAD

**Issue by sacul29** [gwsd2015/Jabberwocky#39]
@twood02 @cctoombs 

I worked on trying to refine my algorithm. 

I made it so I could build a pseudo-syntax tree. It is in a python script and it breaks down the program by using scope parents. It is a non binary tree but it can let me see the complexity of the program.

I also added the ability to identify for loops and if statements in my code. This should allow me to get statistics about the students code and then use that to help them learn.

All of this code is contained in the script: 
[Python script for syntax tree](https://github.com/gwsd2015/Jabberwocky/blob/master/analysis/java_fake_ast.py)

Related wiki pages for this check:
- [January 10th](https://github.com/gwsd2015/Jabberwocky/wiki/20150110_lab_notebook)
- [January 11](https://github.com/gwsd2015/Jabberwocky/wiki/20150111_LabNotebook)
- [January 14](https://github.com/gwsd2015/Jabberwocky/wiki/20150114_LabNotebook)
- [January 18](https://github.com/gwsd2015/Jabberwocky/wiki/20150118_LabNotebook)

**Comment by twood02** [comment]
looking good
