### ISSUE TITLE
Week 22: The Students Demise-- The Instructor Interface

### ISSUE THREAD

**Issue by sacul29** [gwsd2015/Jabberwocky#40]
@cctoombs @twood02 

I have started work on the instructors interface. I accidentally deleted all my files for this week but luckily I was able to get them back with some wizardry. I started using bootstrap to format my files and have been using mysql for class database. I think I might have to switch to nosql because I am having trouble deciding how to store all my data in a relational format. 

Currently the instructor can view all their students and see their workspace locations. They can also view all the features.

The commit is located here: [Instructors interface](https://github.com/gwsd2015/Jabberwocky/commit/ec80530d4aece0795deeedcfbe1792978ecb4696)

**Comment by twood02** [comment]
part of the reason we use github is to avoid accidentally deleting all our
files!  Hopefully you have other backup systems in pace as well.
