### ISSUE TITLE
Week 23: Students Students Students? Weekly commit check

### ISSUE THREAD

**Issue by sacul29** [gwsd2015/Jabberwocky#41]
@cctoombs @twood02 
This week I mainly just focused on redoing my databases. I added the script to create my tables to the repo. 
[Create Tables](https://github.com/gwsd2015/Jabberwocky/blob/master/create_table.sql)

I also worked on the student interface. You can now select students from the class list and see the features they have unlocked.
[Student view](https://github.com/gwsd2015/Jabberwocky/blob/master/instructor/php/student_view.php)

**Comment by twood02** [comment]
sounds good.  Keep your final demo in mind and be sure that what you are building will lead towards that goal.
