### ISSUE TITLE
Week 24: A roadblock...

### ISSUE THREAD

**Issue by sacul29** [gwsd2015/Jabberwocky#42]
@cctoombs @twood02 

Unfortunately this week I have made little progress. I evaluated the way I was identifying the different items in a program(e.g. while and for loops, if statements, etc...) and it turns out I left out some huge edge cases so I have to redo how I identify them. I am working on manually identifying them by just parsing the text by hand. I am actively looking for a new way to do this.

**Comment by twood02** [comment]
I think you really want to investigate something like http://www.antlr.org/  It will have moderately high startup overhead for you to learn how to use it, but it will give you a much much more detailed understanding of the student's code.
